### ISSUE TITLE
AntiPattern.io and ToEatApp

### ISSUE THREAD

**Issue by jcdavison** [OpenSourceShowAndTell/SanFrancisco2016#3]
I've lots of stuff to show and demonstrate :)

http://toeatapp.startuplandia.io/
code base is: https://github.com/jcdavison/to_eat_app

http://antipattern.io
code base is: https://github.com/AntiPatternIO/antipattern
antipattern is mine too I just host it on a different account for reasons I can't quite remember in this moment, but look at the commit history, it is all me.  

jd@startuplandia.io for questions ⚡

**Comment by elof** [comment]
Awesome. +1 and will see you on Friday!
