### ISSUE TITLE
Talk Submission: Building a Mature Analytics Workflow [RJMetrics]

### ISSUE THREAD

**Issue by mattmonihan** [OpenSourceShowAndTell/SanFrancisco2016#4]
### Building a Mature Analytics Workflow

> Analytics teams have a workflow problem today. Too often, analysts operate in isolation, and this creates suboptimal outcomes. Knowledge is siloed. We too often rewrite analyses that a colleague had already written. We fail to grasp the nuances of datasets that we’re less familiar with. We differ in our calculations of a shared metric. As a result, organizations suffer from reduced decision speed and reduced decision quality.
> 
> Analytics doesn’t have to be this way. In fact, the playbook for solving these problems already exists — on our software engineering teams.
> 
> The same techniques that software engineering teams use to collaborate on the rapid creation of quality applications can apply to analytics. We believe it’s time to build an open set of tools and processes to make that happen.

[More info on our Medium post](https://medium.com/@jthandy/building-a-mature-analytics-workflow-the-analyst-collective-viewpoint-7653473ef05b#.keviqn2h3).

[Get started using it (Github)](https://github.com/analyst-collective/wiki/wiki/Setting-up-Analyst-Collective).

**Comment by elof** [comment]
Talked with you. Sorry you won't be able to make this event, but hope we can work on something together soon!
